### ISSUE TITLE
User update receta admite distintos tipos de rol

### ISSUE THREAD

**Issue by carolina-gonzalez-129** [carolina-gonzalez-129/Proyecto-Server-NodeJS#5]
![image](https://github.com/user-attachments/assets/6932d865-1324-4f5b-a5ea-5c9ee8661a9b)
El rol con 1 corresponde al admin el 2 a un user comun y el 3 a un editor. Se esta mostrando el get x id q como comentaba en el issue anterior va a permitir mostrar las recetas q un user cargo

**Comment by carolinuwu** [comment]
![image](https://github.com/user-attachments/assets/a09e52a6-2327-4dee-aad3-6fe11fd067ea)
